name: Pre-release

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  create_release_candidate:
    name: Create release candidate
    uses: davidsonbrsilva/versioning-workflow/.github/workflows/create-pre-release-template.yml@feature/parametrizing-branch-names
    with:
      main_branch: "main"
      feature_branches: "feature"
      hotfix_branches: "hotfix"
    permissions:
      contents: write
