name: Pre-release Template

on:
  workflow_call:
    outputs:
      version:
        description: The new generated version
        value: ${{ jobs.create_release.outputs.version }}

jobs:
  get_last_version:
    name: Get last version
    runs-on: ubuntu-latest
    outputs:
      last_version: ${{ steps.get_last_version.outputs.last_version }}
      is_release_candidate: ${{ steps.get_last_version.outputs.is_release_candidate }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get last version
        id: get_last_version
        uses: davidsonbrsilva/versioning-workflow/actions/latest-version-obtaining@main

  generate_first_release_candidate_version:
    name: Generate first release candidate version
    runs-on: ubuntu-latest
    needs: get_last_version
    outputs:
      version: ${{ steps.add_rc_suffix.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate next release version
        id: generate_next_release
        uses: davidsonbrsilva/versioning-workflow/actions/release-versioning@main
        with:
          origin_branch: ${{ github.head_ref }}
          head_commit: ${{ github.event.pull_request.head.sha }}
          base_commit: ${{ github.event.pull_request.base.sha }}
          last_version: ${{ needs.get_last_version.outputs.last_version }}

      - name: Add release candidate suffix
        id: add_rc_suffix
        run: |
          new_tag=${{ steps.generate_next_release.outputs.version }}-rc-1
          echo "version=$new_tag" >> $GITHUB_OUTPUT
          echo "New generated version: $new_tag."
    if: ${{ !needs.get_last_version.outputs.is_release_candidate }}

  increment_release_candidate_version:
    name: Increment release candidate version
    runs-on: ubuntu-latest
    needs: get_last_version
    outputs:
      version: ${{ steps.increment_rc_suffix.outputs.version }}
    steps:
      - name: Increment release candidate suffix
        id: increment_rc_suffix
        run: |
          regex="([0-9]+)\.([0-9]+)\.([0-9]+)-rc-([0-9]+)"

          if [[ ${{ needs.get_last_version.outputs.last_version }} =~ $regex ]]; then
            major_version="${BASH_REMATCH[1]}"
            minor_version="${BASH_REMATCH[2]}"
            patch_version="${BASH_REMATCH[3]}"
            rc_version="${BASH_REMATCH[4]}"

            rc_version=$((rc_version + 1))
            new_tag=${major_version}.${minor_version}.${patch_version}-rc-${rc_version}
            echo "version=$new_tag" >> $GITHUB_OUTPUT
            echo "New generated version: $new_tag."
            exit 0
          fi

          echo "The version ${{ needs.get_last_version.outputs.last_version }} does not match a valid release candidate version."
          exit 1
    if: ${{ needs.get_last_version.outputs.is_release_candidate == 'true' }}

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      [
        generate_first_release_candidate_version,
        increment_release_candidate_version,
      ]
    permissions:
      contents: write
    outputs:
      version: ${{ steps.create_release.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        id: create_release
        uses: davidsonbrsilva/versioning-workflow/actions/release-creation@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.generate_first_release_candidate_version.outputs.version || needs.increment_release_candidate_version.outputs.version }}
          target_commit: ${{ github.event.pull_request.head.sha }}
          pre_release: true
    if: |
      always() &&
      ((needs.generate_first_release_candidate_version.result == 'success' && needs.increment_release_candidate_version.result == 'skipped') ||
      (needs.generate_first_release_candidate_version.result == 'skipped' && needs.increment_release_candidate_version.result == 'success')
      )
