name: Release

on:
  push:
    branches: ["main"]

jobs:
  create_release:
    name: Create release
    uses: davidsonbrsilva/versioning-workflow/.github/workflows/create-release-template.yml@v0
    with:
      main_branch: "main"
      feature_branches: "feature"
      hotfix_branches: "hotfix"
    permissions:
      contents: write
  upsert_major_version: # Optional
    name: Upsert major version
    needs: create_release
    permissions:
      contents: write
    uses: davidsonbrsilva/versioning-workflow/.github/workflows/upsert-major-version-template.yml@v0
    with:
      version: ${{ needs.create_release.outputs.version }}
