name: Major Version Upserting

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  upsert_major_version:
    name: Upsert major version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upsert major tag
        run: |
          regex="([0-9]+)\.([0-9]+)\.([0-9]+)"

          if [[ ${{ inputs.version }} =~ $regex ]]; then
            major_version="${BASH_REMATCH[1]}"
            tag_name=v${major_version}

            # Delete previous tag
            git push origin :refs/tags/$tag_name

            # Target most recent commit
            # git tag -fa $tag_name

            # Push new reference
            git push origin --tags

            echo "$tag_name updated successfully."
            exit 0
          fi

          echo "${{ inputs.version }} does not match a valid version."
          exit 1
